apiVersion: storage.k8s.io/v1beta1
kind: StorageClass
metadata:
  name: managed-nfs-storage
  labels:
    app: {{ template "nfs-storage.name" . }}
    chart: {{ template "nfs-storage.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
provisioner: {{ .Values.nfsClient.provisionerName }}
