apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.rbac.saName }}
  labels:
    app: {{ template "nfs-storage.name" . }}
    chart: {{ template "nfs-storage.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
